# -*- coding: utf-8 -*-
"""Squirrel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6uWj4nsRMz5OJKfN8OH-3XagpCyP0DN

# New Section
"""

!pip install ultralytics opencv-python numpy matplotlib Pillow

from google.colab import drive
drive.mount('/content/drive')

import os
import matplotlib.pyplot as plt
from ultralytics import YOLO
from PIL import Image
import cv2
import numpy as np

path_to_dataset = "/content/drive/MyDrive/Squirrel Detection.v4i.yolo26"

"""
data set should look like this
yolo_dataset/
├── data.yaml
├── train/
│   ├── images/
│   └── labels/
├── valid/
│   ├── images/
│   └── labels/
└── test/
    ├── images/
    └── labels/
"""

image_files = os.listdir(path_to_dataset + "/train/images/")
print(image_files)

label_files = os.listdir(path_to_dataset + "/train/labels/")
print(label_files)

image_files_view = image_files[:4]
path_to_images = path_to_dataset + "/train/images/"

fig, axes = plt.subplots(1, 4, figsize=(15, 5))

for i, filename in enumerate(image_files_view):
    full_path = os.path.join(path_to_images, filename)
    img = Image.open(full_path)
    axes[i].imshow(img)
    axes[i].set_title(filename, fontsize=10)
    axes[i].axis("off")

plt.tight_layout()
plt.show()

# class_id center_x center_y width height

path_to_images = path_to_dataset + "/train/images/"
path_to_labels = path_to_dataset + "/train/labels/"

pairs = []

for img in image_files:
    img_name = os.path.splitext(img)[0]

    for label in label_files:
        label_name = os.path.splitext(label)[0]

        if img_name == label_name:
            pairs.append((img, label))

print(pairs)

fig, axes = plt.subplots(1, 4, figsize=(15, 5))

for i, pair in enumerate(pairs[:4]):
    img_filename, label_filename = pair

    img_path = os.path.join(path_to_images, img_filename)
    label_path = os.path.join(path_to_labels, label_filename)

    img = Image.open(img_path)
    width, height = img.size

    axes[i].imshow(img)
    axes[i].set_title(img_filename, fontsize=10)
    axes[i].axis("off")

    with open(label_path) as f:
        for line in f:
            print("bbox: " + line)

            parts = line.split()
            class_num = int(parts[0])
            center_x = float(parts[1])
            center_y = float(parts[2])
            b_width = float(parts[3])
            b_height = float(parts[4])

            # Convert YOLO coordinates to pixel coordinates.
            # YOLO coordinates are required by the model.
            # Pixel coordinates are required for visualization.
            x1 = (center_x - b_width / 2) * width
            y1 = (center_y - b_height / 2) * height
            box_w = b_width * width
            box_h = b_height * height

            rect = plt.Rectangle(
                (x1, y1),
                box_w,
                box_h,
                linewidth=1.5,
                edgecolor="red",
                facecolor="none",
            )

            axes[i].add_patch(rect)
            axes[i].text(
                x1,
                y1 - 4,
                str(class_num),
                color="red",
                fontsize=7,
                fontweight="bold",
            )

plt.tight_layout()
plt.show()

yaml_file = path_to_dataset + "/data.yaml"

MODEL = "yolo26n.pt"

model = YOLO(MODEL)
model.train(data=str(yaml_file), epochs=50, imgsz=640)
model.val(data=str(yaml_file))

custom_image_path = "/content/drive/MyDrive/squirrel2.jpeg"

model = YOLO("runs/detect/train/weights/best.pt")
results = model.predict(source=custom_image_path, save=True, conf=0.25)

custom_image_path = "/content/drive/MyDrive/sq5.PNG"

model = YOLO("runs/detect/train/weights/best.pt")
results = model.predict(source=custom_image_path, save=True, conf=0.25)